### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by jimhopp** [jimhopp/frederic#42]
Some fields must not be empty (Visit date for one.)

**Comment by jimhopp** [comment]
@suzannecooper: my plan is to make the following fields required:
- Client
  - First Name
  - Last Name
- Visit
  - Vincentians
  - Visit Date

Sound reasonable? Any others you'd suggest?

**Comment by jimhopp** [comment]
I also added an asterisk to the end of the required field names. Can you update the doc to indicate those fields are required?

**Comment by suzannecooper** [comment]
Hi Jim -

Yes, I'll have a look and will update the documentation. I'm a little under
the gun on the work front this week - and have out of town family coming in
for Easter - so may not have a chance to act on this until next week. Hope
that isn't a problem.

Have a great Easter weekend!

Suzanne

**Comment by jimhopp** [comment]
No worries, next week is fine.

Happy Easter!
